services:
  frontend:
    build:
      context: ./services/frontend
    container_name: frontend
    environment:
      - PORT=80
      - ADD_SERVICE_URL=http://add
      - SUBTRACT_SERVICE_URL=http://subtract
      - MULTIPLY_SERVICE_URL=http://multiply
      - DIVIDE_SERVICE_URL=http://divide
      - CACHE_TYPE=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_URL=jdbc:postgresql://postgres:5432/postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_DRIVER=org.postgresql.Driver
      - CHAOS_ENABLED=${CHAOS_ENABLED:-false}
      - CHAOS_PERCENT=${CHAOS_PERCENT:-}
    ports:
      - "8000:80"
    restart: "no"
    depends_on:
      - add
      - subtract
      - multiply
      - divide
      - redis
      - postgres

  add:
    build:
      context: ./services/add
    container_name: add
    environment:
      - PORT=80
      - CHAOS_ENABLED=${CHAOS_ENABLED:-false}
      - CHAOS_PERCENT=${CHAOS_PERCENT:-}
    restart: "no"
    ports:
      - "8001:80"

  subtract:
    build:
      context: ./services/subtract
    container_name: subtract
    environment:
      - PORT=80
      - ADD_SERVICE_URL=http://add
      - CHAOS_ENABLED=${CHAOS_ENABLED:-false}
      - CHAOS_PERCENT=${CHAOS_PERCENT:-}
    restart: "no"
    depends_on:
      - add
    ports:
      - "8002:80"

  multiply:
    build:
      context: ./services/multiply
    container_name: multiply
    environment:
      - PORT=80
      - CHAOS_ENABLED=${CHAOS_ENABLED:-false}
      - CHAOS_PERCENT=${CHAOS_PERCENT:-}
    restart: "no"
    ports:
      - "8003:80"

  divide:
    build:
      context: ./services/divide
    container_name: divide
    environment:
      - PORT=80
      - CHAOS_ENABLED=${CHAOS_ENABLED:-false}
      - CHAOS_PERCENT=${CHAOS_PERCENT:-}
    restart: "no"
    ports:
      - "8004:80"

  redis:
    image: redis:alpine
    container_name: redis
    restart: "no"
    command: redis-server
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: "no"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
