{{- if and (eq .Values.database.type "postgres") .Values.database.postgres.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "calculator-microservice-java.fullname" . }}-postgres
  labels:
    {{- include "calculator-microservice-java.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  clusterIP: None  # Headless service for StatefulSet
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "calculator-microservice-java.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
{{- end }}
