{{- if and (eq .Values.database.type "postgres") .Values.database.postgres.deploy }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "calculator-microservice-java.fullname" . }}-postgres
  labels:
    {{- include "calculator-microservice-java.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.database.postgres.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.database.postgres.password | quote }}
  POSTGRES_DB: {{ .Values.database.postgres.database | quote }}
{{- end }}
