{{- if and (eq .Values.cache.type "redis") .Values.cache.redis.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "calculator-microservice-java.fullname" . }}-redis
  labels:
    {{- include "calculator-microservice-java.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "calculator-microservice-java.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
{{- end }}
